let clothes = [];

clothes.push("T-shirt");
clothes.push("Jeans");
clothes.push("Jacket");
clothes.push("Sneakers");
clothes.push("Hat");

clothes.pop();
clothes.push("Hoodie");

console.log(clothes[2]); // This will log "Jacket"

let favCar = {};

favCar.color = "Red";

favCar.convertible = false; // You can set it to true or false based on your preference

console.log(favCar);